### ISSUE TITLE
404 when click JavaDocs in Overview section

### ISSUE THREAD

**Issue by agabrys** [codehaus-plexus/codehaus-plexus.github.io#1]
Steps:

1. open http://codehaus-plexus.github.io/plexus-utils/
2. click JavaDocs in Overview section
3. website redirect to http://codehaus-plexus.github.io/plexus-utils/apidocs/index.html
4. return 404

**Comment by hboutemy** [comment]
I just re-published full plexus-utils site content, with javadoc

**Comment by agabrys** [comment]
Fixed. Thanks.
